version: "3.9"

services:
  php:
    container_name: php-7.4
    build:
      dockerfile: Dockerfile
    volumes:
      - /home/sites:/home/sites
      - /home/sites/docker/php-7.4/custom.php.ini:/usr/local/etc/php/conf.d/custom.php.ini
      - /home/sites/docker/php-7.4/custom.www.conf:/usr/local/etc/php-fpm.d/zzz-www.conf
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
    networks:
      sites:
        ipv4_address: 172.100.0.4
networks:
  sites:
    external: true
    name: sites
